"use client";
import Link from "next/link";
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from "lucide-react";
import { cn } from "@/lib/utils";
export interface AdminPaginationProps { currentPage: number; totalPages: number; baseUrl: string; params?: Record<string, string | number | undefined>; siblingCount?: number; className?: string; }
function range(s: number, e: number) { return Array.from({ length: e - s + 1 }, (_, i) => s + i); }
export function AdminPagination({ currentPage, totalPages, baseUrl, params = {}, siblingCount = 1, className }: AdminPaginationProps) {
  if (totalPages <= 1) return null;
  const p = Math.max(1, Math.min(currentPage, totalPages));
  const h = (pg: number) => { const sp = new URLSearchParams(); sp.set("page", String(pg)); for (const [k, v] of Object.entries(params)) { if (v !== undefined && v !== "") sp.set(k, String(v)); } return `${baseUrl}?${sp.toString()}`; };
  const pages: (number | string)[] = [];
  if (totalPages <= 7) { pages.push(...range(1, totalPages)); } else { const l = p - siblingCount, r = p + siblingCount; pages.push(1); if (l > 2) pages.push("..."); else if (l === 2) pages.push(2); pages.push(...range(Math.max(2, l), Math.min(totalPages - 1, r))); if (r < totalPages - 1) pages.push("..."); else if (r === totalPages - 1) pages.push(totalPages - 1); pages.push(totalPages); }
  return (<nav className={cn("flex items-center justify-between", className)}><p className="text-sm text-gray-500">第 {p} / {totalPages} 页</p><div className="flex items-center gap-1"><Link href={h(1)} className={cn("inline-flex h-9 w-9 items-center justify-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50", p === 1 && "pointer-events-none opacity-50")} aria-disabled={p === 1} tabIndex={p === 1 ? -1 : undefined}><ChevronsLeft className="h-4 w-4" /></Link><Link href={h(p - 1)} className={cn("inline-flex h-9 w-9 items-center justify-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50", p === 1 && "pointer-events-none opacity-50")} aria-disabled={p === 1} tabIndex={p === 1 ? -1 : undefined}><ChevronLeft className="h-4 w-4" /></Link>{pages.map((pg, i) => typeof pg === "string" ? <span key={`e-${i}`} className="h-9 w-9 inline-flex items-center justify-center text-gray-400">…</span> : <Link key={pg} href={h(pg)} className={cn("inline-flex h-9 w-9 items-center justify-center rounded-lg border text-sm font-medium", pg === p ? "border-blue-600 bg-blue-600 text-white" : "border-gray-200 text-gray-600 hover:bg-gray-50")} aria-current={pg === p ? "page" : undefined}>{pg}</Link>)}<Link href={h(p + 1)} className={cn("inline-flex h-9 w-9 items-center justify-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50", p === totalPages && "pointer-events-none opacity-50")} aria-disabled={p === totalPages} tabIndex={p === totalPages ? -1 : undefined}><ChevronRight className="h-4 w-4" /></Link><Link href={h(totalPages)} className={cn("inline-flex h-9 w-9 items-center justify-center rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50", p === totalPages && "pointer-events-none opacity-50")} aria-disabled={p === totalPages} tabIndex={p === totalPages ? -1 : undefined}><ChevronsRight className="h-4 w-4" /></Link></div></nav>);
}
